[[main]]
  identifier = "articles"
  name = "Articles"
  url = "articles"
  weight = 1

[[main]]
  identifier = "notes"
  name = "Notes"
  url = "notes"
  weight = 2

[[main]]
  identifier = "blog"
  name = "Blog"
  url = "blog"
  weight = 3